"""Demo fixture — 评委无需配置即可体验的示例扫描结果"""

DEMO_REPORT = {
    "task_id": "cr-demo-20260820-001",
    "status": "completed",
    "source": "demo",
    "repo_url": "https://github.com/example/flask-vulnerable-app",
    "summary": {
        "critical": 1,
        "high": 2,
        "medium": 3,
        "low": 2,
        "info": 1,
        "total": 9,
    },
    "findings": [
        {
            "id": "CR-001",
            "severity": "critical",
            "category": "SQL Injection",
            "file": "app/routes/users.py",
            "line": 42,
            "code_snippet": 'cursor.execute(f"SELECT * FROM users WHERE id = {user_id}")',
            "description": "直接使用 f-string 拼接 SQL 查询，攻击者可通过 user_id 参数注入任意 SQL 语句。",
            "recommendation": "使用参数化查询：cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,))",
            "cwe": "CWE-89",
            "confidence": 0.98,
            "agent": "agent_1_static",
        },
        {
            "id": "CR-002",
            "severity": "high",
            "category": "Command Injection",
            "file": "app/utils/network.py",
            "line": 18,
            "code_snippet": 'os.system(f"ping -c 1 {host}")',
            "description": "用户输入直接传入 os.system()，可执行任意系统命令。",
            "recommendation": "使用 subprocess.run() 配合参数列表，禁止 shell=True。",
            "cwe": "CWE-78",
            "confidence": 0.95,
            "agent": "agent_1_static",
        },
        {
            "id": "CR-003",
            "severity": "high",
            "category": "Hardcoded Secret",
            "file": "config.py",
            "line": 7,
            "code_snippet": 'SECRET_KEY = "super-secret-key-12345"',
            "description": "Flask SECRET_KEY 硬编码在源码中，可被用于伪造 Session Cookie。",
            "recommendation": "从环境变量读取：os.environ.get('SECRET_KEY')，并确保 .env 不入版本控制。",
            "cwe": "CWE-798",
            "confidence": 0.99,
            "agent": "agent_2_semantic",
        },
        {
            "id": "CR-004",
            "severity": "medium",
            "category": "XSS (Cross-Site Scripting)",
            "file": "app/templates/profile.html",
            "line": 12,
            "code_snippet": "<div>{{ user.bio | safe }}</div>",
            "description": "使用 |safe 过滤器绕过 Jinja2 自动转义，存储型 XSS 风险。",
            "recommendation": "移除 |safe，或在后端对 user.bio 做 HTML 实体编码。",
            "cwe": "CWE-79",
            "confidence": 0.90,
            "agent": "agent_2_semantic",
        },
        {
            "id": "CR-005",
            "severity": "medium",
            "category": "Insecure Deserialization",
            "file": "app/utils/cache.py",
            "line": 31,
            "code_snippet": "data = pickle.loads(cache_data)",
            "description": "反序列化不可信数据可导致远程代码执行（RCE）。",
            "recommendation": "改用 json.loads()，或对 pickle 数据做签名验证。",
            "cwe": "CWE-502",
            "confidence": 0.85,
            "agent": "agent_1_static",
        },
        {
            "id": "CR-006",
            "severity": "medium",
            "category": "Path Traversal",
            "file": "app/routes/files.py",
            "line": 25,
            "code_snippet": 'return send_file(f"uploads/{filename}")',
            "description": "filename 未做路径净化，攻击者可用 ../../etc/passwd 读取任意文件。",
            "recommendation": "使用 werkzeug.utils.secure_filename() 过滤，并限制路径前缀。",
            "cwe": "CWE-22",
            "confidence": 0.88,
            "agent": "agent_3_verifier",
        },
        {
            "id": "CR-007",
            "severity": "low",
            "category": "Missing CSRF Protection",
            "file": "app/routes/auth.py",
            "line": 55,
            "code_snippet": "@app.route('/change-password', methods=['POST'])",
            "description": "修改密码接口未启用 CSRF 防护，可被跨站请求伪造攻击。",
            "recommendation": "启用 Flask-WTF 的 CSRFProtect，或在表单中添加 csrf_token。",
            "cwe": "CWE-352",
            "confidence": 0.80,
            "agent": "agent_2_semantic",
        },
        {
            "id": "CR-008",
            "severity": "low",
            "category": "Verbose Error Messages",
            "file": "app/__init__.py",
            "line": 15,
            "code_snippet": "app.config['DEBUG'] = True",
            "description": "生产环境开启 DEBUG 模式会暴露堆栈跟踪和内部路径。",
            "recommendation": "生产环境强制 DEBUG=False，使用日志记录错误。",
            "cwe": "CWE-209",
            "confidence": 0.75,
            "agent": "agent_2_semantic",
        },
        {
            "id": "CR-009",
            "severity": "info",
            "category": "Dependency Outdated",
            "file": "requirements.txt",
            "line": 3,
            "code_snippet": "Flask==2.0.1",
            "description": "Flask 2.0.1 已有已知安全漏洞（CVE-2023-30861），建议升级。",
            "recommendation": "升级到 Flask>=2.3.2",
            "cwe": "N/A",
            "confidence": 1.0,
            "agent": "agent_3_verifier",
        },
    ],
    "analysis": {
        "duration_seconds": 4.2,
        "agents_used": 4,
        "files_scanned": 23,
        "lines_of_code": 1847,
        "llm_model": "Qwen2.5-Coder-7B-Instruct (local)",
        "mode": "local-gpu",
    },
    "report_urls": {
        "json": "/reports/cr-demo-20260820-001.json",
        "sarif": "/reports/cr-demo-20260820-001.sarif",
        "pdf": None,
    },
    "digital_signature": None,
    "completed_at": "2026-08-20T15:00:00Z",
}
